#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# KUBECONFIG fanciness for multiple cluster config management
KUBEHOME=$HOME/.kube
# KUBECONFIG=""
# for file in $KUBEHOME/{.,}*(N); do
#   if [[ $file != "$KUBEHOME/kubectx" && $file != "$KUBEHOME/kubens" &&
#       $file != "$KUBEHOME/cache" && $file != "$KUBEHOME/http-cache" ]] ; then
#     if [[ $KUBECONFIG == "" ]] then
#       KUBECONFIG=$file
#     else
#       export KUBECONFIG=$KUBECONFIG:$file
#     fi
#   fi
# done

export JAVA_HOME=$(/usr/libexec/java_home)
export M2_HOME=/usr/local/Cellar/maven/3.5.3/libexec
export TC_CONFIG_PATH=$HOME/code/goro/pg-config-source

export CARGO_BIN=$HOME/.cargo/bin
export GOROOT=/usr/local/go
export GOROOT_BIN=$GOROOT/bin
export GOPATH=/Users/adam.margherio/code/go
export GOBIN=$GOPATH/bin

export ISTIO_PATH=$HOME/bin/istio/current
export ISTIO_BIN=$HOME/bin/istio/current/bin
export GCLOUD_BIN=$HOME/bin/google-cloud-sdk/bin
export KREW_BIN=${KREW_ROOT:-$HOME/.krew}/bin

export PYTHON_LOCAL_BIN=$HOME/Library/Python/3.6/bin

export LOCAL_BIN=$HOME/bin
export ANDROID_HOME=/Users/adam.margherio/Library/Android/sdk
export FLUTTER_BIN=$LOCAL_BIN/flutter/bin
export DOOM_DIR=$HOME/.doom.d
export EMACS_BIN=$HOME/.emacs.d/bin

# export PATH
path=("$path[@]" "$HOME/.local/bin" "$JAVA_HOME" "$M2_HOME" "$TC_CONFIG_PATH" "$CARGO_BIN" \
	"$GOROOT" "$GOROOT_BIN" "$GOPATH" "$GOBIN" \
	"$ISTIO_PATH" "$ISTIO_BIN" "$GCLOUD_BIN" "$KREW_BIN" \
	"$PYTHON_LOCAL_BIN" "$LOCAL_BIN" "$ANDROID_HOME" "$FLUTTER_BIN" \
	"$DOOM_DIR" "$EMACS_BIN")
typeset -U PATH path
export PATH

# adding in haskell/ghc/cabal/stack
source $HOME/.ghcup/env

source $HOME/.zsecrets
export VAULT_ADDR="https://vault.toyotaconnected.net"

# prompt things
PURE_PROMPT_SYMBOL=";"
PURE_PROMPT_VICMD_SYMBOL=":<;"
