#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz compinit 
compinit

source $HOME/.zshenv

gen_single_kubeconfig()

if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi

#source /usr/local/etc/bash_completion.d
source /usr/local/share/zsh/site-functions

gen_single_kubeconfig() {
  curr_dir=$(pwd)

  cd ~/.kube
  rm -rf config && touch ./config # this may be damaging to local docker kubernetes config...
  yq m -a ./config ./{am-tmna-*,am-mnao-*,au-*} >> config

  cd $curr_dir
}

gen_random_string () {
	local val=$(LC_CTYPE=C tr -cd "a-z0-9" < /dev/urandom | tr -dc '[:alnum:]' | fold -w 6 | head -n 1)
  echo "$val"
}

troubleshoot_pod () {
  pod_suffix=$(gen_random_string)
	pod_name="troubleshooting-amargherio-${pod_suffix}"
	kubectl run "$pod_name" -i --tty --image="amtmnaacr.azurecr.io/ops/ops-toolkit:1.0.0" -n infra --restart=Never --overrides='{ "apiVersion": "v1", "spec": { "imagePullSecrets": [{"name": "acr"}] } }' -- bash

  kubectl delete po -n infra "$pod_name"
}


alias vi=nvim
alias vim=nvim
#alias kcep=kubectl get pods -o json | jq '.items[] | select(.status.reason!=null) | select(.status.reason | contains("Evicted")) | "kubectl delete po \(.metadata.name) -n \(.metadata.namespace)"' | xargs -n 1 bash -c
alias ls=exa
alias grep=rg
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/kustomize kustomize
