#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source $HOME/.zshenv

# And set the path
PATH=$PATH:$GOBIN
PATH=$PATH:$DOTNET_BIN
PATH=$PATH:$LOCAL_BIN

# and now that the path is built, export it
export PATH